\c songs_dev;

INSERT INTO songs (name, artist, album, time, url, is_favorite) VALUES 
('Timbeano', 'Mixael Cabrera', 'Llego lo que te gusta...', '4:30', 'https://open.spotify.com/track/0KbnShzRqp2daq4CY09AWi?si=9603574aece14759', true),
('Te Dejo Libre', 'Manolito Simonet y su Trabuco', 'Te Dejo Libre', '5:52', 'https://open.spotify.com/track/2QNZ9VGRK1PScMwWWrth3o', true),
('Tres Dias', 'Havana D`Primera', 'Cantor del Pueblo', '5:21', 'https://open.spotify.com/track/33hjoPb45TjMp0TGYDawsv', false),
('Lamento Yoruba', 'Havana D`Primera', 'Cantor del Pueblo', '5:22', 'https://open.spotify.com/track/4l2OciEiV3tH4qEh30B27Q?si=cc17e5f66a5145d1', false),
('Me va a Extrañar', 'DLG', 'Lo Esencial', '4:40', 'https://open.spotify.com/track/6SDPyxHxVWPnklOqpmLNs5', true),
('Hasta que vuelvas conmigo', 'Marc Anthony', 'Libre', '4:51', 'https://open.spotify.com/track/2jQFh3tNFsqWNViCNf0ePP?si=4759049cce524d53', false),
('Confio en Tí', 'Pablo FG', 'Un poquito de Tó', '5:15', 'https://open.spotify.com/track/2nb31JbJcnsWdDcyrTFMn4', false),
('Noche de Entierro', 'Daddy Yankee, Wisin & Yandel, Zion, Hector El Father, Tonny Tun Tun', 'MAs Flow - LOs Benjamins', '4:23', 'https://open.spotify.com/track/6ksWMnPcHNyNoNf3y1BQCO', true),
('Sexy Movimiento', 'Wisin & Yandel', 'La Historia del Dúo', '3:33', 'https://open.spotify.com/track/6ppRLoJ9FETtXtxWmYhcVd', true),
('Gasolina', 'Daddy Yankee', 'Gasolina', '3:13', 'https://open.spotify.com/track/6jWY6my69XvcXjn2OYeiRE?si=91134ba6efe6439d', false),
('Danca Kizomba', 'Stony', 'null', '3:49', 'https://open.spotify.com/track/6BLLoHOQqY3rOpMoaO6yHv', true),
('It`s Gonna be me', 'Nsync', 'NO Strings Attached', '3:12', 'https://open.spotify.com/track/2AW37v0bDyuOzGP3XnmFuA', true),
('End of the Road', 'Boyz II Men', 'Cooleyhighharmony', '5:51', 'https://open.spotify.com/track/3l3xTXsUXeWlkPqzMs7mPD', false),
('One Sweet Day', 'Mariah Carey & Boyz II Men', 'Daydream', '4:41', 'https://open.spotify.com/track/7ySbfLwdCwl1EM0zNCJZ38', true),
('The Call', 'Backstreet Boys', 'Black & Blue', '3:24', 'https://open.spotify.com/track/1mxTCArq9EhSg4QPGqhjhT', false),
('Shape of my Heart', 'Backstreet Boys', 'Black & Blue', '3:50', 'https://open.spotify.com/track/35o9a4iAfLl5jRmqMX9c1D', false),
('Despacito', 'Luis Fonsi & Daddy Yankee', 'Vida', '3:50', 'hhttps://open.spotify.com/track/6habFhsOp2NvshLv26DqMb', true),
('Memories', 'Maroon 5', 'Jordi(Deluxe)', '3:09', 'https://open.spotify.com/track/4cktbXiXOapiLBMprHFErI', false),
('I Wanna Know', 'Joe', 'My name is Joe', '4:57', 'https://open.spotify.com/track/1m2xMsxbtxv21Brome189p', false),
('Te Quise Olvidar', 'MDO', 'Subir al Cielo', '4:22', 'https://open.spotify.com/track/4UGv3IQYXPj9oR2RMkarWy', true),
('Sin Tí', 'MDO', 'Subir al Cielo', '3:24', 'https://open.spotify.com/track/4WaoXAWY014qh0vcT0POZi', false),
('Azul', 'Cristian Castro', 'Grandes Hits', '4:19', 'https://open.spotify.com/track/6pHCJmx9FXnMwEqB0LWUEH', true),
('A puro Dolor', 'Son By Four', 'Son by 4', '3:30', 'https://open.spotify.com/track/28upjDakWVnHAgW2anm273', true),
('Nowhere', '112', 'Pleasure & Pain', '3:54', 'https://open.spotify.com/track/5hz9jVare2nvrNvKHbkqIy', false),
('Perfect', 'Ed Sheeran', '+(Deluxe', '4:23', 'https://open.spotify.com/track/0tgVpDi06FyKpA1z0VMD4v', false),
('Same Girl', 'R. Kelly & Usher', 'Double Up', '4:13', 'https://open.spotify.com/track/6OSmeoh8kXhCfz9WqvzDoJ', true),
('Lola, Lola', 'David Calzado & Charanga Habanera', 'Tremendo Delirio', '6:32','https://open.spotify.com/track/1qrKuaNmeiuKnph9hde0OC', true);